### ISSUE TITLE
Window resizing problem

### ISSUE THREAD

**Issue by ksurdacki** [vizorvr/vizor-create#1]
![window-resizing-problem](https://cloud.githubusercontent.com/assets/10234093/5719951/c688260a-9b1d-11e4-93fe-eb17e9d7a106.png)

After some mysterious combination on web browser window resizing create.vizor.io renders wider than web browser window causing horizontal scroll bar to be displayed.

Google Chrome version 39.0.2171.95 m

**Comment by kschzt** [comment]
closing this as the UI has changed so much after this. please reopen if you see this happen.
