### ISSUE TITLE
Bug: Breadcrumb navigation bug when using the "Loop framework" preset in a certain graph.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#106]
1. Open this graph:
http://create.vizor.io/fthr/fish-follows-star-2/edit

2. Navigate to inside the "Object 2 (source? the fish)" subgraph.

3. Pay attention to the breadcrumb. It now correctly shows you are inside the fish subgraph.-

4. From the preset menu, add "Loop framework"

5. Click "Edit" to go inside "Loop framework"

6. Pay attention to the breadcrumb. It now incorrectly shows that the loop framework is placed under "TARGET (the star)" subgraph!

**Comment by kschzt** [comment]
fixed in staging by something else
