### ISSUE TITLE
Viewport plugins don't react to resize events

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#13]

**Comment by uucidl** [comment]
also viewport does not update when the window itself changes

**Comment by uucidl** [comment]
also if the intention of viewport is to give the resolution that we are rendering into, in a subgraph which renders to texture rather than to the framebuffer, it is conceivable of it to return that texture's size

**Comment by kschzt** [comment]
the current thinking for retrieving the output texture size is that the texture dimensions can be retrieved from the subgraph output texture, then written into a register and read back into the shader. closing this one now; @uucidl let us know if you have any issues! and merci! :)
