### ISSUE TITLE
Editor breaks when connecting output to output

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#159]
1. press 2 twice (add two subgraphs)
2. connect either texture output to the other texture output

**Comment by wd-vizor** [comment]
![cables_bug](https://cloud.githubusercontent.com/assets/11323864/8617346/0b05f3d4-272d-11e5-9bc9-5027d694020f.gif)
![cables](https://cloud.githubusercontent.com/assets/11323864/8617345/0b05488a-272d-11e5-87ba-87eff6e7d4a2.gif)
