### ISSUE TITLE
Loading saved files & node layer disappears

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor-create#184]
I was switching between files Burgertime, Burgertime3 & Burgertime2 & upon loading Burgertime2 (in that order), node layer disappeared and i could not click "Root" to get back to top level of graph.

![node layer bug](https://cloud.githubusercontent.com/assets/6858525/8741795/35798abc-2c88-11e5-88ad-b571fc79e80a.png)

**Comment by mattatgit** [comment]
@kschzt Not sure if this the same issue or not, but now when loading burgertime 2 then burgertime 3, i cannot use tab key to hide node layer & cannot stop or pause the graph.

After a reload i can hide & show the node layer but still cannot pause or stop the graph (buttons change state but do not function)
![screen shot 2015-07-20 at 12 02 27 pm](https://cloud.githubusercontent.com/assets/6858525/8770223/564ac84a-2ed7-11e5-8d75-79775e334100.png)

**Comment by kschzt** [comment]
Reproduced:

1. Save a Copy, open copy
2. Add 3D Particles
3. Open some other file
4. Open the copy
5. Breaks when trying to restore output proxy connection
