### ISSUE TITLE
Noodles are drawn wrong after hidpi

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#204]
1. New
2. Paste VR Clean preset

**Comment by kschzt** [comment]
<img width="1268" alt="screen shot 2015-07-22 at 00 48 33" src="https://cloud.githubusercontent.com/assets/293426/8813305/1db5acfe-300b-11e5-9b4d-bf918be9dacc.png">

**Comment by wd-vizor** [comment]
+1 @garland220 has also experienced this
