### ISSUE TITLE
Textbox content does not propagate across multiuser

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor-create#207]
![screen shot 2015-07-22 at 3 10 57 pm](https://cloud.githubusercontent.com/assets/11323864/8822319/bdef3a22-308e-11e5-8f8e-d7a5a2da659b.png)

In this example, @mattatgit connected a textbox to the URL input, and an image showed up in the image box, but I did not see the text entered into the text box.

**Comment by kschzt** [comment]
could be same as #219
