### ISSUE TITLE
Implement front page design

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#213]

**Comment by kschzt** [comment]
![vizor_landing](https://cloud.githubusercontent.com/assets/293426/8827334/cbe3eaaa-3094-11e5-8f79-f1cb7689c3ab.png)

**Comment by kschzt** [comment]
old palette
![dbe18620f7bcc0055aab4dfb425233fa52002f88](https://cloud.githubusercontent.com/assets/293426/8829216/1cb4142e-309e-11e5-89d4-a6e2756f5ba9.png)

**Comment by mattatgit** [comment]
![vizor mark outline 3px copy vizor copy 1x](https://cloud.githubusercontent.com/assets/6858525/8847367/3cc9e97c-3158-11e5-970a-9e4c2b37eb15.png)
![vizor mark outline 3px copy vizor copy 2x](https://cloud.githubusercontent.com/assets/6858525/8847368/3d10a132-3158-11e5-9b2b-e3cc6fffc3c9.png)
Here are 1x & 2x PNGs for the logo. Typeface i'm using is Open Sans (so no licensing fees), but you could continue to use Roboto for the time being if you want, given that its still being used throughout the UI. @kschzt I can share the Sketch file with you if you'd like – but not much point if you don't have the app yet.
