### ISSUE TITLE
Editing a subgraph node (where two of the same exist) edits another node in the graph

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor-create#220]
http://destroy.vizor.io/reiska/broken-plasma-psychedelic-connections-3/edit

1. Rename the lower 'Plasma Psychedelic' node 
> The top one gets renamed instead

2. Connect the texture node into the lower Plasma Psychedelic's texture connection
> It connects to the top one instead

This is a simplified script from http://destroy.vizor.io/reiska/broken-plasma-psychedelic-connections/edit - @juho dragged two instances of plasma psychedelic from the presets menu into the script.

**Comment by kschzt** [comment]
couldn't reproduce. this was probably something that happened while it was briefly possible to receive your own messages back from the server in dev.
