### ISSUE TITLE
Fix rendering so stuff can be turned on/off on boolean.

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor-create#269]

**Comment by fthr** [comment]
This means the old "enabled" slot functionality.  We talked about removing the "enabled" slot and instead doing it via a preference setting or a plugin. The specifics of that are unclear to me.

**Comment by kkananen** [comment]
Fixed a lot of bugs to do with turning stuff on / off. Also the enabled input is now entirely gone, enabling / disabling stuff should be done with conditional logic. 

Leaving ticket open for now as we'll need to be able to conditionally add stuff into scenes; right now this isn't possible, we might need an 'object3d array' to be fed into the scene.
