### ISSUE TITLE
Showing a texture on a plane is broken

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor-create#271]
I've gotten it working sometime but many times not: http://destroy.vizor.io/fthr/show-a-texture-on-a-plane-in-threejs/edit When it worked, the texture looped 4 times horizontally and 2 times verticaly. Instead, there should be some UV options (scale, rotation, x&y offset) --antti

**Comment by kkananen** [comment]
This is not 'broken' anymore - the textures shouldn't loop now. However we'll need more UV controls that should be separate tickets
