### ISSUE TITLE
Fix node ghosting

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor-create#279]

**Comment by kschzt** [comment]
sometimes nodes get two UI's, causing all kinds of issues. investigate and fix

**Comment by kkananen** [comment]
Might be related - the first edit done after forking seems to be corrupt somehow:
1. Open any graph (e.g. http://destroy.vizor.io/reiska/ghost-node-test/)
2. Add two nodes (e.g. press 4 twice to add two float nodes) - the graph should be forked at this stage
3. Delete the two nodes you just added (marquee select and press backspace)
4. Reload (Ctrl/Cmd+R)
> one of the deleted nodes is back!

**Comment by kschzt** [comment]
unable to reproduce lately, must have been a plugin stability issue in three branch
