### ISSUE TITLE
A particle system (PointCloud object and material)

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#291]
Point cloud object:
http://threejs.org/docs/#Reference/Objects/PointCloud

Point cloud material:
http://threejs.org/docs/#Reference/Materials/PointCloudMaterial

**Comment by fthr** [comment]
Point cloud object:
http://threejs.org/docs/#Reference/Objects/PointCloud

Point cloud material:
http://threejs.org/docs/#Reference/Materials/PointCloudMaterial
