### ISSUE TITLE
Lights: Adding another light needs a stop/play before the second light shows.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#320]
Reproduce:
-Add Base preset.
-Add a sphere and connect to scene
-Duplicate the directional light preset
-Go inside either directional light, and connect an oscillator preset into the "intensity" slot of the light.
-No oscillating light seems to be present
-Press stop/play
-Oscillation of the light becomes visible

**Comment by kschzt** [comment]
unable to reproduce this ...  @fthr
