### ISSUE TITLE
Implement top menu bar design

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#334]

**Comment by mattatgit** [comment]
This prototype has basic behaviour for file menu open / close
https://beta.atomic.io/d/Mj88LUvbeGiX

Menubar control states
https://www.dropbox.com/s/sozd2hcby86022c/Screenshot%202015-09-04%2010.53.19.png?dl=0

Sketch file location
Vizor UI > Vizor UI Comps > Editor UI > Vizor Editor UI components 150904

Desktop fonts location
Vizor > Fonts

The Sketch file contains states for all main navbar controls + file menu states.
Does not yet contain the states for the bottom playbar.

**Comment by kschzt** [comment]
This is where the top menu bar lives: https://github.com/vizorvr/vizor-create/blob/develop/views/editor.handlebars

The page is rendered by GraphController: https://github.com/vizorvr/vizor-create/blob/develop/controllers/graphController.js#L64

The dialogs are opened in eg. https://github.com/vizorvr/vizor-create/blob/develop/browser/scripts/application.js#L1405 and click handlers are bound at https://github.com/vizorvr/vizor-create/blob/develop/browser/scripts/application.js#L2046-L2051

**Comment by imgrby** [comment]
found action handlers only for first set of nav buttons: file menu (with subs), new graph, graph tree (currently in sidebar). the rest 9 buttons (scale, rotate, add object; inspector, add patch, save patch; camera views, editor, zoom) should have no actions attached for now?

**Comment by mattatgit** [comment]
Some explanation:
* Add patch will open a dialogue browser that shows all the patches (currently presets & plugins)
* Add object does the same for an object library browser (doesnt exist yet)
*Save patch is "save as patch" from file menu. 
* Inspector will open a beefed up version of the preferences for a patch currently accessed via the cog icon on subgraph patches. 
* Editor / Patch layer is a additionaly UI hook to the current "show / hide patch layer with Tab key" ie if in Editor. the icon shown will be "patch layer", if in Patch layer the icon shown will be "Editor" 
* Zoom, Camera Views, Scale, Rotate don't exist yet so yeah, lets add them with no actions attached for now

**Comment by imgrby** [comment]
what works:  file menu with subs, new graph. 
sign in temporary displays current login modal.  editor/cam-view visibility should be switched in proper function later in application.js, as well as actions for other buttons.
TODO: develop menu behavior at least for 1280 and 1024, as long as current was designed for 1366px

**Comment by mattatgit** [comment]
![updated navbar](https://cloud.githubusercontent.com/assets/6858525/9723246/d9c6ce6a-5571-11e5-849e-dbe516b3422e.png)
Cleaned up some icons that were incorrect line weight. Also height of navbar & breadcrumb &  type size on breadcrumb & colours of background of navbar& breadcrumb
file name: Vizor_Navbar_Updated_150907

**Comment by mattatgit** [comment]
![screenshot 2015-09-11 09 18 00](https://cloud.githubusercontent.com/assets/6858525/9821057/a16341c2-586c-11e5-996b-1cb04b808b53.png)
icons are being cut off in top menu bar
