### ISSUE TITLE
Implement Chat design

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor-create#336]

**Comment by mattatgit** [comment]
See Sketch file: Vizor Editor UI components 150904
https://www.dropbox.com/s/d2crmk31n07njy6/Screenshot%202015-09-04%2018.11.04.png?dl=0

**Comment by imgrby** [comment]
@imgrby todo: if chat is collapsed and chat button in top nav bar clicked - expand chat, not hide.
