### ISSUE TITLE
Materials: Turn "Transparent" on by default

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#343]
I think it's the more common usecase.

Affects all materials with "transparent" slot.

**Comment by kkananen** [comment]
not sure if we should do this, there is a performance penalty & this might cause some draw order problems

**Comment by fthr** [comment]
Well, in any case I'll turn it on in all the presets, as I want always to have the controls for blending, opacity and double sided at hand. So it's not strictly necessary to turn it on in the plugin. Just would save one toggle value from the common presets.

**Comment by kschzt** [comment]
closing
