### ISSUE TITLE
Implement new notifications style

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor-create#373]
This one is lower priority than app UI chrome & chat, but just lining it up for when they are done.

Sketch file with notifications components is Vizor Chat + Notifications 150908

Behaviour for animation is here
https://www.dropbox.com/s/488bn73ye0iy47c/Vizor%20notification%20animation.mov?dl=0

**Comment by imgrby** [comment]
@imgrby todo: add fallback to growl and people manager if message is about following but there's no userpic url

**Comment by imgrby** [comment]
@imgrby todo: if message type icon not found among svg symbols - display default icon. (currently works if no type specified)
