### ISSUE TITLE
Inputs (mouse/keyboard) not working

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#43]
See this graph for replication: http://create.vizor.io/fthr/mousebutton/edit

Clicking mouse should give true bools.

**Comment by kschzt** [comment]
Keyboard input seems to be working fine, but have replicated mouse issue

**Comment by kschzt** [comment]
The reason is that the mouse events are being swallowed by the editing canvas on top of the webgl canvas. So this only happens when editing the graph. Not sure whether it should listen to events on that layer too..
