### ISSUE TITLE
Loading issue with "Load scene from URL" plugin

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#47]
Apparent on this graph:

http://create.vizor.io/fthr/twisty-gradient-robots-3/edit

Load that, press play, and you're supposed to see a bunch of robots. Instead you only see the backround cube. Navigate to "Root" of the graph, and the robots appear.

This graph uses loops, and is quite CPU/GPU heavy. On graphs that are less heavy the problem isn't present, for example: http://create.vizor.io/kschzt/robot-in-a-castle/edit

**Comment by kschzt** [comment]
fixed, it was an async loading issue
