### ISSUE TITLE
Marquee selection freezes on screen in a certain mesh preset subgrapoh

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#50]
To reproduce:
1) new graph, press play
2) load the preset: mesh with camera material and light and transforms
3) go inside the mesh subgraph
4) load a plugin using the search box: mesh/null
5) disconnect the existing "cube" mesh from the mesh slot in "mesh" subgraph
6) connect the "null" plugin to that mesh slot
7) use a marquee to select the 3 orbit camera sliders
8) blue marquee square should now freeze on the edit canvas

Screenshots attached.

![marquee-freeze-bug-2](https://cloud.githubusercontent.com/assets/6809021/7773477/639357ea-00ad-11e5-8622-ac1247eb9c8d.jpg)
![marquee-freeze-bug-1](https://cloud.githubusercontent.com/assets/6809021/7773478/63953466-00ad-11e5-87c5-53137922c6f8.jpg)

**Comment by kschzt** [comment]
This seems to be fixed - please confirm @fthr and close

**Comment by fthr** [comment]
Tested, can't make this bug happen again, so closing.
