### ISSUE TITLE
Change “enabled” slot on the subgraph to be on/off icon instead

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor-create#68]

**Comment by kschzt** [comment]
@fthr I'm not sure about this... 
- is this a button?
- would we still connect eg. booleans to the slot? 
- how does this improve things? 

right now all slot names are UTF8 text, personally I don't believe changing english names to icons makes it simpler, on the contrary. thoughts?

**Comment by wd-vizor** [comment]
This is one of those @mattatgit /redesign-area things that probably shouldn't be an issue yet.
