### ISSUE TITLE
Aspect Ratio not fired?

### ISSUE THREAD

**Issue by afferently** [vizorvr/vizor-create#72]
The aspect ratio preset updates when you resize the browser.

Unfortunately it does not update when you turn on or off or resize the editor's panes.

Resizing the browser, stoping and playing, etc resolves it.

Correct:
![screen shot 2015-06-05 at 16 14 26](https://cloud.githubusercontent.com/assets/717353/8010758/e54d9dc4-0baa-11e5-8f48-2bf078e09707.png)

With pane closed it stays stretched:
![screen shot 2015-06-05 at 16 15 06](https://cloud.githubusercontent.com/assets/717353/8010764/ed91832e-0baa-11e5-9449-b446b26bb9ed.png)

With all the panes open it stays shrunk:
![screen shot 2015-06-05 at 16 15 11](https://cloud.githubusercontent.com/assets/717353/8010766/f116b942-0baa-11e5-996b-88dae4b98e02.png)

**Comment by kschzt** [comment]
already fixed
