### ISSUE TITLE
Assets: Private assets + Vizor default assets

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#81]
Instead of "All assets are global" like we have now, we want user to be able to view 2 categories of assets: "My own assets", and "Vizor default assets". Vizor default assets will be coordinated by Antti using Creative Commons materials. These could be tabs on top of the asset panel.

For the vizor default assets, some kind of superuser interface is needed where the superuser can add and remove them.

**Comment by wd-vizor** [comment]
Closing this since the new design is coming and the issues will need to be relevant to that.
