### ISSUE TITLE
Preset:Sketchfab style click-and-drag to rotate and object.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#95]

**Comment by fthr** [comment]
https://sketchfab.com/models/52dcb62f9113470d84f6299de9299910

This preset should give the user the exact functionality of that Sketchfab embed. 

Show a 3D object in the middle of the screen, and clicking and draging on the mouse horizontally rotates it in a smooth way with smooth  easing/acceleration, and dragging vertically changes the elevation (but not all the way around).

**Comment by wd-vizor** [comment]
Closing this since the new design is coming and the issues will need to be relevant to that.

But Matt, please see that example. :)

**Comment by mattatgit** [comment]
yep, i've seen it.
